# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03ced759962f7fdc616a56156f0b94478e9034657c2572ea908eb1ada34075e444b0e396353a7a51a19254a98b940d222ae51dd186d0e2ebfc6249128590b7ec

test:
  secret_key_base: a4ecf63897bfcaa3d2351be9a028b3696040b171030a3bf5e0ad4ec49e5219db2d00da9a23237ed4cb9f8ecdedfd798836553335c12416fbe8b276e783479030

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
